"""Guards against drift between the pinned versions, the lock file, and CI, and
checks that the configuration contract in .env.example matches config.py.

.python-version and .nvmrc are the source of truth for the Python and Node
versions. These tests run everywhere pytest does (locally and in CI), so they
only assert things that must hold in both. Host-specific checks live in
scripts/check_env.py.
"""

import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def read(relative_path: str) -> str:
    return (ROOT / relative_path).read_text()


def search(pattern: str, text: str, source: str) -> str:
    match = re.search(pattern, text, re.MULTILINE)
    assert match, f"Couldn't find {pattern!r} in {source}"
    return match.group(1)


@pytest.fixture(scope="module")
def pinned_python() -> str:
    return read(".python-version").strip()


@pytest.fixture(scope="module")
def pinned_node() -> str:
    return read(".nvmrc").strip().lstrip("v")


def test_running_python_matches_pinned_version(pinned_python):
    running = f"{sys.version_info.major}.{sys.version_info.minor}"
    assert running == pinned_python


def test_ci_versions_match_pinned_versions(pinned_python, pinned_node):
    ci = read(".github/workflows/ci.yml")
    assert search(r'PYTHON_VERSION:\s*"([^"]+)"', ci, "ci.yml") == pinned_python
    assert search(r'NODE_VERSION:\s*"([^"]+)"', ci, "ci.yml") == pinned_node


def test_lock_file_compiled_with_pinned_python(pinned_python):
    lock = read("requirements.lock")
    compiled_with = search(
        r"autogenerated by pip-compile with Python (\d+\.\d+)", lock, "lock"
    )
    assert compiled_with == pinned_python, (
        "Regenerate the lock with the pip-compile command in its header."
    )


def test_slidekick_package_importable():
    import slidekick

    assert Path(next(iter(slidekick.__path__))) == ROOT / "src" / "slidekick"


def test_numpy_and_opencv_round_trip_an_image():
    import cv2
    import numpy as np

    frame = np.zeros((8, 8, 3), dtype=np.uint8)
    frame[2:6, 2:6] = (0, 128, 255)

    ok, encoded = cv2.imencode(".png", frame)
    assert ok
    assert np.array_equal(cv2.imdecode(encoded, cv2.IMREAD_COLOR), frame)


@pytest.mark.parametrize("command", ["ruff", "pytest", "pip-compile"])
def test_dev_tool_on_path(command):
    assert shutil.which(command), f"{command} is not installed; check requirements.lock"


# --- configuration -----------------------------------------------------------


def test_env_example_exists():
    assert (ROOT / ".env.example").is_file(), (
        "Restore it with `git checkout -- .env.example`"
    )


@pytest.mark.parametrize("path", [".env", ".venv"])
def test_local_environment_files_are_ignored_by_git(path):
    result = subprocess.run(
        ["git", "check-ignore", "--quiet", "--no-index", path], cwd=ROOT, check=False
    )
    assert result.returncode == 0, f"{path} must be listed in .gitignore"


def test_env_example_documents_every_setting():
    read_by_config = set(
        re.findall(r'"(SLIDEKICK_\w+)"', read("src/slidekick/config.py"))
    )
    documented = set(
        re.findall(r"^#?\s*(SLIDEKICK_\w+)=", read(".env.example"), re.MULTILINE)
    )
    assert read_by_config, "Couldn't find any SLIDEKICK_ settings in config.py"
    assert read_by_config <= documented, (
        f"Add to .env.example: {', '.join(sorted(read_by_config - documented))}"
    )


def test_env_example_has_no_real_values():
    # Every setting is commented out or empty, so copying it never commits a value.
    for line in read(".env.example").splitlines():
        if line and not line.startswith("#"):
            key, _, value = line.partition("=")
            assert not value.strip(), f"{key} has a value in .env.example"


def test_default_settings_are_valid_on_this_os():
    from slidekick.config import load_settings

    settings = load_settings(environ={}, env_file=ROOT / ".env.example")
    assert settings.model_path.is_file(), f"Missing model: {settings.model_path}"
