"""Guards against drift between the Lando image, the lock file, and CI.

These run everywhere pytest does (Lando and CI), so they only assert things
that must hold in both. Container-specific checks live in
scripts/check_env.py (`lando doctor`).
"""

import re
import shutil
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


def read(relative_path: str) -> str:
    return (ROOT / relative_path).read_text()


def search(pattern: str, text: str, source: str) -> str:
    match = re.search(pattern, text, re.MULTILINE)
    assert match, f"Couldn't find {pattern!r} in {source}"
    return match.group(1)


@pytest.fixture(scope="module")
def dockerfile_python() -> str:
    return search(
        r"^FROM python:(\d+\.\d+)", read("docker/dev/Dockerfile"), "Dockerfile"
    )


@pytest.fixture(scope="module")
def dockerfile_node() -> str:
    return search(
        r"deb\.nodesource\.com/setup_(\d+)\.x",
        read("docker/dev/Dockerfile"),
        "Dockerfile",
    )


def test_running_python_matches_dockerfile(dockerfile_python):
    running = f"{sys.version_info.major}.{sys.version_info.minor}"
    assert running == dockerfile_python


def test_ci_versions_match_dockerfile(dockerfile_python, dockerfile_node):
    ci = read(".github/workflows/ci.yml")
    assert search(r'PYTHON_VERSION:\s*"([^"]+)"', ci, "ci.yml") == dockerfile_python
    assert search(r'NODE_VERSION:\s*"([^"]+)"', ci, "ci.yml") == dockerfile_node


def test_lock_file_compiled_with_dockerfile_python(dockerfile_python):
    lock = read("requirements.lock")
    compiled_with = search(
        r"autogenerated by pip-compile with Python (\d+\.\d+)", lock, "lock"
    )
    assert compiled_with == dockerfile_python, "Regenerate the lock with `lando lock`."


def test_lando_lock_command_matches_lock_header():
    # pip-compile records its own invocation in the lock header. If the
    # `lando lock` command drifts from it, every re-lock produces a noisy diff.
    lando_cmd = search(
        r"^\s*cmd:\s*(pip-compile .+)$", read(".lando.yml"), ".lando.yml"
    )
    header_cmd = search(r"^#\s+(pip-compile .+)$", read("requirements.lock"), "lock")
    assert lando_cmd.strip() == header_cmd.strip()


def test_slidekick_package_importable():
    import slidekick

    assert Path(next(iter(slidekick.__path__))) == ROOT / "src" / "slidekick"


def test_numpy_and_opencv_round_trip_an_image():
    import cv2
    import numpy as np

    frame = np.zeros((8, 8, 3), dtype=np.uint8)
    frame[2:6, 2:6] = (0, 128, 255)

    ok, encoded = cv2.imencode(".png", frame)
    assert ok
    assert np.array_equal(cv2.imdecode(encoded, cv2.IMREAD_COLOR), frame)


@pytest.mark.parametrize("command", ["ruff", "pytest", "pip-compile"])
def test_dev_tool_on_path(command):
    assert shutil.which(command), f"{command} is not installed; check requirements.lock"
